I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 332, in script
    Ilyria "A good choice for keeping dangers at a distance. There are 24 arrows; use them wisely."
Exception: Sayer 'Ilyria' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 332, in script
    Ilyria "A good choice for keeping dangers at a distance. There are 24 arrows; use them wisely."
  File "D:\Git-Huh\Fragmented\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Git-Huh\Fragmented\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Ilyria' is not defined.

Windows-10-10.0.22635 AMD64
Ren'Py 8.1.3.23091805
Fragmented 1.0
Mon Oct 30 10:19:42 2023
