I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script5.rpy", line 17, in script
    monster "YOUUUUuuu..."
Exception: Sayer 'monster' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script5.rpy", line 17, in script
    monster "YOUUUUuuu..."
  File "D:\Git-Huh\Fragmented\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Git-Huh\Fragmented\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'monster' is not defined.

Windows-10-10.0.22635 AMD64
Ren'Py 8.1.3.23091805
Fragmented 1.0
Tue Dec  5 20:02:53 2023
