I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script3.rpy", line 99, in script
    egon "Aye, it has. But it will stand tall again. It must."
Exception: Sayer 'egon' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script3.rpy", line 99, in script
    egon "Aye, it has. But it will stand tall again. It must."
  File "D:\Git-Huh\Fragmented\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Git-Huh\Fragmented\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'egon' is not defined.

Windows-10-10.0.22635 AMD64
Ren'Py 8.1.3.23091805
Fragmented 1.0
Sun Nov 12 21:55:22 2023
